In [9]:
import numpy as np
years = np.arange(2000,3200)
years = years[(years%7==0) & (years%5 != 0)]
for i in range(len(years)): print(str(years[i] ) ,end=", ")

2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199, 

In [11]:
def factorial(n):
    if n == 1:
        return 1
    return n*factorial(n-1)
inp = int(input().strip())
factorial(inp)

120

In [ ]:
inp = int(input().strip())
dic = {i:i**2 for i in range(1,inp+1)}
print(dic)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

In [35]:
import re
inp = re.split(r"\s*,\s*",input().strip())
print(list(map(lambda x:re.search(r"\d+",x).group(),inp)))
print(tuple(map(lambda x:re.search(r"\d+",x).group(),inp)))

['5', '3']
('5', '3')


In [38]:
class InputString:
    def __init__(self):
        self.s = ""
    def getString(self):
        self.s = input()
    def printString(self):
        print(self.s.upper())
        
a = InputString()
a.getString()
a.printString()



53AA


In [ ]:
import numpy as np
import re
Q = lambda D: np.sqrt(2*D*50/30)
print(Q(np.array(list(map(int,re.split(r"\s*,\s*",input().strip()))))))



array([4.0824829 , 3.16227766, 2.5819889 ])

In [ ]:
import numpy as np

x ,y = map(int,input().strip().split(","))
print(np.array([[i*j for i in range(x) ]for j in range(y)]))


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [62]:
import re

words = re.split(r"\s*,\s*",input().strip())
print(words)
print(sorted(words,key=lambda x: ord(x[0])))


['zt43h3wugh', 'qgf', 'fahb', 'abd', 'bax', 'dga', 'cgag']
['abd', 'bax', 'cgag', 'dga', 'fahb', 'qgf', 'zt43h3wugh']


In [ ]:
import re
import numpy as np
inp = np.array(re.split(r"\s*,\s*",input().strip()))
np.vectorize(lambda x:bool(re.fullmatch(r"[(?=*.(a-z))(?=*.(A-Z))(?=*.(0-9))(?=*.($#@))]",x)))(inp)

    

array([ True,  True, False])

In [ ]:
import pandas as pd

pd.Dataframe()

In [1]:

print(input().upper())

In [ ]:
import re



print(" ".join(sorted(re.split(r"\s*,\s*",input().strip()),key=lambda x: ord(x[0]))))

In [ ]:
import numpy as np
inp = np.array(input().strip(" ").split(","))
inp = inp[np.vectorize(lambda x:bool(x % 5 ==0))(np.array(list(map(lambda x:int(x,2) ,inp))))]
print(" ".join(inp))



0101 1010


In [ ]:
import numpy as np
x = np.arange()
for i in x:
    